org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
kotlin.code.style=official
kotlin.stdlib.default.dependency=false

pluginGroup=io.coderf.arklab.templates
pluginName=ArkLab BaseActivity Templates
pluginVersion=1.1.1
pluginSinceBuild=242
pluginUntilBuild=253.*

# Local Android Studio (Narwhal). Change if your install path differs.
androidStudioPath=C:\\Program Files\\Android\\Android Studio Narwhal
